ALTER TABLE "video_views"
ADD COLUMN "domain" TEXT,
ADD COLUMN "cdn_bytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN "p2p_bytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN "watched_sec" INTEGER NOT NULL DEFAULT 0;
